### ISSUE TITLE
Users should be able to create a task 

### ISSUE THREAD

**Issue by sarahpaz** [sarahpaz/pineappler#3]

**Comment by omenking** [comment]
You need to create the following:
- [ ] Goals Controller
- [ ] Goal Model
- [ ] Tasks Controller
- [ ] Task Model
- [ ] EntityTasks Controller
- [ ] EntityTask Model

You need to set a root route:
- [ ] The default route should go to goals#index

## goals#index

This will be the page that users see when they are logged in

- [ ] There should be a list of goals with a list of tasks under each goal.
- [ ] There should be a button to add a new goal
- [ ] There should be a button edit an existing goal
- [ ] There should be a button to add a task to a goal
- [ ] They should see a scheduler view underneath the list of goals which is a list of entity tasks based on their upcoming date.
- [ ] There should be a section of today's tasks, and the user should be able to check them off.
## goals#form

This will be the form that allows users to create a goal.
A user gets to this form by clicking `New Goal` on the goals#index

- [ ] A goal should have a name
- [ ] A goal should have a description

## tasks#form

This will be the form that allows users to create a task
A user gets to this form by clicking `Add Goal` on the goals#index listed under the goal they wish to add this task to.

- [ ] A task should have a name
- [ ] A task should be able to take in a list of dates that are comma-delimited eg. 2019-05-05, 2019-05-11, 2019-06-12

When a task is saved in the TasksController create or update action it needs to iterate through these dates and create an entity_task for each date. These entity tasks are the actual tasks the users will check off. The task model itself is just the template.
